package projectManagementSystem.projectManagement.model;

import java.time.LocalDate;

import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

@AllArgsConstructor
@NoArgsConstructor
@Entity
@Data
public class AdminProject {

    // @Id: Marks this field as the primary key in the database table.
    // @GeneratedValue: Specifies how the primary key value is automatically generated.
    // GenerationType: Specifies that the primary key is generated by the database.
    @Id
    @GeneratedValue(strategy = GenerationType.AUTO)
    private Long projectId;

    private String title;
    // Represents the start date of the project.
    private LocalDate startDate;

    // Represents the end date of the project.
    private LocalDate endDate;

    // Represents the description of the project.
    private String description;

    // Represents the admin ID associated with the project.
    private int admin_id;
    
    
    
}

